---
routers:
   - hostname: CAP-A10
     main_interface: Gi5/9
     sub_int:
       Gi5/9.2077:
         ip: 192.2.41.73/30
       Gi5/9.2177:
         vrf: RDS
         ip: 192.2.31.65/30
         nei: 192.2.31.66
       Gi5/9.2277:
         vrf: RIX
         ip: 192.2.21.65/30
         nei: 192.2.21.66
       Gi5/9.2449:
         vrf: RVP_SURETE
         ip: 192.2.172.37/30
         nei: 192.2.172.38
       Gi5/9.2477:
         vrf: RVP_GTB
         ip: 192.2.141.65/30
         nei: 192.2.141.66
       Gi5/9.2577:
         vrf: RVP_WIFI
         ip: 192.2.197.74/30
         nei: 192.2.197.73
       Gi5/9.2802:
         vrf: RVP_SHAREDSERVICES
         ip: 192.2.248.190/30
         nei: 192.2.248.189
       Gi5/9.3252:
         vrf: RVP_LEGACYSURETE
         ip: 192.2.39.22/30
         nei: 192.2.39.21
       Gi5/9.3377:
         vrf: RVP_ITEC
         ip: 192.2.181.65/30
         nei: 192.2.181.66
     remote_as: 64911
     PE: DC2-B1
     PE_interface: Gi0/7/1/5
     speed: 1G
   - hostname: SCH-A10
     main_interface: Gi5/1
     sub_int:
       Gi5/1.2087:
         ip: 192.2.42.197/30
       Gi5/1.2190:
         vrf: RDS
         ip: 192.2.33.73/30
         nei: 192.2.33.74
       Gi5/1.2290:
         vrf: RVP_WIFI
         ip: 192.2.197.106/30
         nei: 192.2.197.105
       Gi5/1.2303:
         vrf: RVP_ITEC 
         ip: 192.2.181.41/30  
         nei: 192.2.181.42 
       Gi5/1.2801:
         vrf: RVP_SHAREDSERVICES 
         ip: 192.2.246.94/30
         nei: 192.2.246.93 
     remote_as: 64911
     PE: DC2-B1
     PE_interface: Gi0/7/1/3
     speed: 1G